http.host: "0.0.0.0"
xpack.monitoring.enabled: false

pipeline.ordered: auto
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

queue.type: memory
queue.max_bytes: 1gb

log.level: info

path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs